name: iOS e2e maestro

on:
  push:
    branches: [main]

jobs:
  test:
    name: E2E test
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - name: Install IDB
        run: |
          brew tap facebook/fb
          brew install idb-companion

      - name: Install dependencies
        run: npm install
      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.3

      - name: Generate iOS Project
        run: npx expo prebuild --platform ios --no-install

      - name: Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest

      - name: Install Pods
        working-directory: ./ios
        run: pod install --repo-update

      - name: Build iOS
        working-directory: ./ios
        run: xcodebuild -workspace ./expomaestroactions.xcworkspace -scheme expomaestroactions -configuration Release -sdk iphonesimulator -derivedDataPath build -arch "$(uname -m)"

      - name: Run Simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: "iPhone 15"
          os_version: 17
          erase_before_boot: false

      - name: Wait for Simulator
        run: sleep 30 # Wait for 30 seconds to ensure the simulator is fully up

      - name: Check Simulator Status
        run: |
          xcrun simctl list | grep 'iPhone 15' || { echo "Simulator not found!"; exit 1; }

      - name: Run iOS
        run: xcrun simctl install booted ios/build/Build/Products/Release-iphonesimulator/expomaestroactions.app

      - name: Run Maestro
        run: maestro test maestro/test.yml
        env:
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 100000
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: results
          path: ~/.maestro/tests
