name: Hello World

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: circleci/android:api-30
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: default
          ndk: 21.3.6528147

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install project dependencies
        run: npm install

      - name: Start ADB server
        run: adb start-server

      - name: Create Android emulator
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-30;default;x86_64"

      - name: Start Android emulator
        run: |
          emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82 &

      - name: Install Maestro CLI
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Build and run Expo app
        run: npx expo run:android

      - name: Run Maestro tests
        run: maestro test maestro/test.yml
